# ───────────────────────────────────────────────────────────────
# Build & Publish Settings
# ───────────────────────────────────────────────────────────────
[build]
  # Only install dependencies
  command   = "npm install"
  # Where your serverless functions live
  functions = "functions"
  # Publish from the root (where index.html now lives)
  publish   = "."

# ───────────────────────────────────────────────────────────────
# Netlify Dev (local testing)
# ───────────────────────────────────────────────────────────────
[dev]
  functions = "functions"
  publish   = "."

# ───────────────────────────────────────────────────────────────
# Redirect all URLs to index.html (SPA / SW fallback)
# ───────────────────────────────────────────────────────────────
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
  force  = true

# ───────────────────────────────────────────────────────────────
# Custom Headers: allow embedding in any iframe
# ───────────────────────────────────────────────────────────────
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options         = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *;"
