# ───────────────────────────────────────────────────────────────
# Build & Publish Settings
# ───────────────────────────────────────────────────────────────
[build]
  # Only install dependencies (no `build` script in package.json)
  command   = "npm install"
  # Where your serverless functions live
  functions = "functions"
  # Where your host page + UV assets live
  publish   = "public"

# ───────────────────────────────────────────────────────────────
# Netlify Dev (local testing)
# ───────────────────────────────────────────────────────────────
[dev]
  functions = "functions"
  publish   = "public"
  # If you ever add a local bundler/watch step, you can override:
  # command = "npm run dev"

# ───────────────────────────────────────────────────────────────
# Redirect all URLs to index.html (SPA / service-worker host)
# ───────────────────────────────────────────────────────────────
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
  force  = true

# ───────────────────────────────────────────────────────────────
# Custom Headers
# ───────────────────────────────────────────────────────────────
[[headers]]
  for = "/*"
  [headers.values]
    # Allow embedding this entire site in any <iframe>
    X-Frame-Options         = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *;"
